### PR TITLE
fix LICENSE filename and update license text

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by Twipped** [comment]
What are you using as the basis that the license file must be extensionless? [Github specifically names it LICENSE.txt](https://help.github.com/articles/licensing-a-repository/) in their documentation.

Additionally, it's not necessary update the date every year to maintain the validity of the license.

**Comment by DanielRuf** [comment]
Without the extension and with the proper license content you get the license shown at the top bar at the homepage of the repository next to the number of contributors, releases, commits, ...

**Comment by Twipped** [comment]
Took a bit of digging, but it wasn't the filename at all. Apparently licensee doesn't allow for the library name to exist in the license file any more. Dropping that allowed for the license to be detected.

**Comment by DanielRuf** [comment]
Ok =)

**Pull request closed without merging**
